### PR TITLE
Add unknown flag (ufe82b) substitution

### LINKED ISSUE #73: Cannot find reference to ufe82b glyph
The font contains a glyph named ufe82b, and we don't know where this comes from. U+FE82B is a codepoint in a Private Use Area. Checked the previous version (1.001) and the ufe82b glyph is there too.

### PR DESCRIPTION
**Pull request by miguelsousa**
Fixes #73

### CODE REVIEW

**Comment by miguelsousa** [comment]
Before
before
After
after

**Comment by frankrolf** [comment]
Thank you!
This works very well, however it does only work if the ISO country codes are neatly split up – here for instance by a thin space 0x200A:


If the combinations are chained w/o anything in between, we get this:


Now I wonder – if someone types 🇦 🇦 🇨 🇦– should they expect 

Screen Shot 2021-09-06 at 13 37 40
(behavior after this PR)

or 
Screen Shot 2021-09-06 at 13 38 22
?

I would vote for option 2, and have experimented with editing the GSUB file accordingly – not successfully so far.
Of course, it would be possible to make a list of ”unknown” combinations instead of the catch-all solution proposed, but it seems very verbose. 

Any ideas or suggestions?

**Comment by miguelsousa** [comment]
I agree, the second behavior is the desired one. I swapped the order of the sub and made it not contextual; that seems to have fixed it.
Screen Shot 2021-09-06 at 11 32 09
Screen Shot 2021-09-06 at 11 32 38

**Comment by frankrolf** [comment]
Excellent! 😎

**Pull request merged**
